# Generated by Django 5.0 on 2024-02-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_activo', models.CharField(max_length=100)),
                ('areas', models.CharField(max_length=100)),
                ('tipo_activo', models.CharField(max_length=100)),
            ],
        ),
    ]
