# Generated by Django 5.0 on 2024-02-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_nombre_activo_catalogue_name_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='type_active',
        ),
    ]
