# Generated by Django 5.0 on 2024-02-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ruta_imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
