# Generated by Django 5.0 on 2024-02-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessData', '0002_business_ruta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='ruta_imagen',
        ),
    ]
