# Generated by Django 5.0 on 2023-12-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_activo', models.CharField(max_length=100)),
                ('descripcion_activo', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(choices=[('fisico', 'fisico'), ('logico', 'logico')], max_length=20)),
                ('tipo_activo', models.CharField(choices=[('fisico', 'fisico'), ('intangible', 'intangible'), ('software', 'software')], max_length=20)),
                ('c', models.CharField(max_length=20)),
                ('i', models.CharField(max_length=20)),
                ('d', models.CharField(max_length=20)),
            ],
        ),
    ]
