# Generated by Django 5.0 on 2023-12-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0002_alter_item_descripcion_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracion', models.BooleanField(default=False)),
                ('clave_codigo', models.BooleanField(default=False)),
                ('lugar_planta', models.BooleanField(default=False)),
                ('departamento_area', models.BooleanField(default=False)),
                ('responsable_propietario', models.BooleanField(default=False)),
                ('nombre_activo', models.BooleanField(default=False)),
                ('descripcion_activo', models.BooleanField(default=False)),
                ('tipo_ubicacion', models.BooleanField(default=False)),
                ('tipo_activo', models.BooleanField(default=False)),
                ('cid', models.BooleanField(default=False)),
                ('criticidad', models.BooleanField(default=False)),
                ('modelo_activo', models.BooleanField(default=False)),
                ('sistema_software', models.BooleanField(default=False)),
                ('nivel_clasificacion', models.BooleanField(default=False)),
            ],
        ),
    ]
