# Generated by Django 5.0 on 2023-12-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0003_inventarify'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='option1',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='option2',
            field=models.IntegerField(blank=True, choices=[('Muy alto', 'Muy Alto'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('Muy bajo', 'Muy bajo')], null=True),
        ),
    ]
