# Generated by Django 5.0 on 2023-12-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0004_item_option1_item_option2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option2',
        ),
        migrations.AddField(
            model_name='item',
            name='responsable',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='c',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='d',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='i',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_activo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='ubicacion',
            field=models.CharField(max_length=20),
        ),
    ]
