# Generated by Django 5.0 on 2023-12-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0005_remove_item_option1_remove_item_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clasificacion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
