# Generated by Django 5.0 on 2023-12-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0006_item_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.IntegerField(default=''),
        ),
    ]
