# Generated by Django 5.0 on 2023-12-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0007_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
