# Generated by Django 5.0 on 2023-12-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0008_alter_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
