# Generated by Django 5.0 on 2023-12-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0009_alter_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='no',
        ),
    ]
