# Generated by Django 5.0 on 2024-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0010_remove_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
