# Generated by Django 5.0 on 2024-01-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0011_item_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
