# Generated by Django 5.0 on 2024-01-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0012_item_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='no',
        ),
        migrations.AddField(
            model_name='item',
            name='numero',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
