# Generated by Django 5.0 on 2024-01-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0013_remove_item_no_item_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
