# Generated by Django 5.0 on 2024-01-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0015_remove_item_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numero',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
