# Generated by Django 5.0 on 2024-01-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0016_alter_item_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='numero',
        ),
    ]
