# Generated by Django 5.0 on 2024-01-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0017_remove_item_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nombre_activo', models.CharField(max_length=100)),
                ('descripcion_activo', models.TextField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('responsable', models.CharField(default='', max_length=100)),
                ('ubicacion', models.CharField(max_length=20)),
                ('tipo_activo', models.CharField(max_length=20)),
                ('c', models.DecimalField(decimal_places=2, max_digits=20)),
                ('i', models.DecimalField(decimal_places=2, max_digits=20)),
                ('d', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('clasificacion', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
