# Generated by Django 5.0 on 2024-01-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0018_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numero',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion_activo',
            field=models.TextField(max_length=20),
        ),
    ]
