# Generated by Django 5.0 on 2024-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0019_item_numero_alter_item_descripcion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descripcion_activo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='descripcion_activo',
            field=models.TextField(max_length=20),
        ),
    ]
