# Generated by Django 5.0 on 2024-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0020_alter_item_descripcion_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='descripcion_activo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='nombre_activo',
            field=models.CharField(max_length=20),
        ),
    ]
