# Generated by Django 5.0 on 2024-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0022_alter_items_clasificacion_alter_items_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('version', models.IntegerField(max_length=255)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_revision', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
