# Generated by Django 5.0 on 2024-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0023_itembusiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembusiness',
            name='version',
            field=models.IntegerField(),
        ),
    ]
