# Generated by Django 5.0 on 2024-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0024_alter_itembusiness_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembusiness',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
