# Generated by Django 5.0 on 2024-01-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0025_alter_itembusiness_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarify',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='criticidad',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='departamento_area',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='descripcion_activo',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='nivel_clasificacion',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='nombre_activo',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='numeracion',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='responsable_propietario',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='tipo_activo',
        ),
        migrations.RemoveField(
            model_name='inventarify',
            name='tipo_ubicacion',
        ),
    ]
