# Generated by Django 5.0 on 2024-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0026_remove_inventarify_cid_remove_inventarify_criticidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarify',
            name='clave_codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarify',
            name='lugar_planta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarify',
            name='modelo_activo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventarify',
            name='sistema_software',
            field=models.CharField(max_length=100),
        ),
    ]
