# Generated by Django 5.0 on 2024-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0027_alter_inventarify_clave_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_activo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_planta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_software', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventarify',
        ),
    ]
