# Generated by Django 5.0 on 2024-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0028_modelo_planta_sistema_delete_inventarify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='i',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
