# Generated by Django 5.0 on 2024-02-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0029_alter_items_c_alter_items_d_alter_items_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembusiness',
            name='imagen',
        ),
    ]
